#!/usr/bin/env bash
# Links tracked config into place and generates the git indirection file
# that points at the overlay.

export HV_STEP_NAME="symlinks"
export HV_STEP_SCOPE="user"

HV_GIT_CONFIG_HOME="${HV_GIT_CONFIG_HOME:-$HOME/.config/git}"

hv::_pairs() {
  printf '%s\t%s\n' \
    "$HV_ROOT/git/gitconfig"         "$HOME/.gitconfig" \
    "$HV_ROOT/git/gitignore_global"  "$HOME/.gitignore_global" \
    "$HV_ROOT/config/starship.toml"  "$HOME/.config/starship.toml" \
    "$HV_ROOT/zsh/.zprofile"         "$HOME/.zprofile" \
    "$HV_ROOT/zsh/.zshrc"            "$HOME/.zshrc"
}

hv_step_check() {
  local src dst
  while IFS=$'\t' read -r src dst; do
    hv::linked "$src" "$dst" || return 1
  done <<EOF
$(hv::_pairs)
EOF
  hv::linked "$HV_ROOT/bin/hv" "$HOME/.local/bin/hv" || return 1
  [ -f "$HV_GIT_CONFIG_HOME/local" ]
}

# The comment deliberately avoids the word "overlay" -- this file is written
# whether or not an overlay is configured, and a test asserts the no-overlay
# case has no trace of the word.
hv::_write_git_local() {
  local overlay
  overlay="$(hv::config_get HV_OVERLAY)"
  hv::run mkdir -p "$HV_GIT_CONFIG_HOME"
  [ "${HV_DRY_RUN:-0}" = "1" ] && return 0
  {
    printf '# Generated by hv setup. Do not edit this file directly.\n'
    # git silently ignores an include path that does not exist yet, so this
    # does not require the overlay's git/config to already be there -- a
    # freshly configured overlay picks it up the moment the file appears,
    # with no need to re-run this step.
    if [ -n "$overlay" ] && [ "$overlay" != "none" ]; then
      printf '[include]\n\tpath = %s/git/config\n' "$overlay"
    fi
  } > "$HV_GIT_CONFIG_HOME/local"
}

hv_step_run() {
  hv::step 40 "symlinks"

  local src dst f
  while IFS=$'\t' read -r src dst; do
    hv::link "$src" "$dst"
  done <<EOF
$(hv::_pairs)
EOF

  hv::run mkdir -p "$HOME/.local/bin" "$HOME/.zshrc.d" "$HOME/.zsh/cache"

  for f in "$HV_ROOT"/zsh/.zshrc.d/*.zsh; do
    hv::link "$f" "$HOME/.zshrc.d/$(basename "$f")"
  done

  for f in "$HV_ROOT"/bin/*; do
    [ -x "$f" ] || continue
    hv::link "$f" "$HOME/.local/bin/$(basename "$f")"
  done

  hv::_write_git_local

  if [ ! -f "$HOME/.secrets" ] && [ "${HV_DRY_RUN:-0}" != "1" ]; then
    cat > "$HOME/.secrets" <<'EOF'
# Secrets — never commit this file.
# export GITHUB_TOKEN=""
# export ANTHROPIC_API_KEY=""
EOF
    chmod 600 "$HOME/.secrets"
    hv::ok "created ~/.secrets"
  fi

  if [ ! -f "$HOME/.zshrc.d/local.zsh" ] && [ "${HV_DRY_RUN:-0}" != "1" ]; then
    cat > "$HOME/.zshrc.d/local.zsh" <<'EOF'
# Machine-specific config, not tracked anywhere.
# Anything you want on every Mac belongs in your overlay instead.
[[ -f ~/.secrets ]] && source ~/.secrets
EOF
    hv::ok "created ~/.zshrc.d/local.zsh"
  fi

  return 0
}
