#!/usr/bin/env bash
# Links tracked config into place and generates the git indirection file
# that points at the overlay.

export HV_STEP_NAME="symlinks"
export HV_STEP_SCOPE="user"

HV_GIT_CONFIG_HOME="${HV_GIT_CONFIG_HOME:-$HOME/.config/git}"

hv::_pairs() {
  printf '%s\t%s\n' \
    "$HV_ROOT/git/gitconfig"         "$HOME/.gitconfig" \
    "$HV_ROOT/git/gitignore_global"  "$HOME/.gitignore_global" \
    "$HV_ROOT/config/starship.toml"  "$HOME/.config/starship.toml" \
    "$HV_ROOT/zsh/.zprofile"         "$HOME/.zprofile" \
    "$HV_ROOT/zsh/.zshrc"            "$HOME/.zshrc"
}

hv_step_check() {
  local src dst
  while IFS=$'\t' read -r src dst; do
    hv::linked "$src" "$dst" || return 1
  done <<EOF
$(hv::_pairs)
EOF
  hv::linked "$HV_ROOT/bin/hv" "$HOME/.local/bin/hv" || return 1
  hv::_git_local_current
}

# The comment deliberately avoids the word "overlay" -- this file is written
# whether or not an overlay is configured, and a test asserts the no-overlay
# case has no trace of the word.
hv::_git_local_render() {
  local overlay
  overlay="$(hv::config_get HV_OVERLAY)"
  printf '# Generated by hv setup. Do not edit this file directly.\n'
  # git silently ignores an include path that does not exist yet, so this
  # does not require the overlay's git/config to already be there -- a
  # freshly configured overlay picks it up the moment the file appears,
  # with no need to re-run this step.
  if [ -n "$overlay" ] && [ "$overlay" != "none" ]; then
    printf '[include]\n\tpath = %s/git/config\n' "$overlay"
  fi
}

# Existence alone is not enough: an overlay configured (or removed) after
# this file was first written -- e.g. `hv overlay init` run well after
# declining it at step 40 -- must not read as "already converged" just
# because the file happens to exist. Compare against what would be
# generated now, the same pattern hv::docs_current uses for USAGE.md.
hv::_git_local_current() {
  [ -f "$HV_GIT_CONFIG_HOME/local" ] || return 1
  hv::_git_local_render | diff -q - "$HV_GIT_CONFIG_HOME/local" >/dev/null 2>&1
}

hv::_write_git_local() {
  hv::run mkdir -p "$HV_GIT_CONFIG_HOME"
  [ "${HV_DRY_RUN:-0}" = "1" ] && return 0
  hv::_git_local_render > "$HV_GIT_CONFIG_HOME/local"
}

hv::_write_local_zsh_stub() {
  cat > "$HOME/.zshrc.d/local.zsh" <<'EOF'
# Machine-specific config, not tracked anywhere.
# Anything you want on every Mac belongs in your overlay instead.
[[ -f ~/.secrets ]] && source ~/.secrets
EOF
}

# Companion to local.zsh: machine-specific packages, not tracked anywhere.
# Bundled by step 50 alongside the module and overlay Brewfiles. A pure
# comment here reads as empty to 90-check's drift warning (see the comment
# on hv::_untracked_personal_config), so creating it up front never trips
# a false "you have personal packages" the moment setup finishes.
hv::_write_local_brewfile_stub() {
  cat > "${HV_CONFIG_HOME:-$HOME/.config/hv}/local.Brewfile" <<'EOF'
# Your own packages, not tracked anywhere.
# Anything you want on every Mac belongs in your overlay instead.
# cask "chatgpt"
EOF
}

# local.zsh is never a tracked file -- hv::link never touches it -- so any
# symlink found here was left by a previous, non-hv dotfiles setup. Leaving
# it alone would let it go dangling the moment that other repo is cleaned up
# (~/.zshrc sources ~/.zshrc.d/*.zsh unconditionally, so a dangling link
# there breaks every new shell). Reconcile it before the "create if missing"
# check below ever sees it.
hv::_reconcile_local_zsh() {
  local dst="$HOME/.zshrc.d/local.zsh" target

  [ -L "$dst" ] || return 0
  target="$(readlink "$dst")"

  # A symlink we created ourselves would point inside this repo. We never
  # create one for local.zsh, but skip out if that ever changes.
  case "$target" in
    "$HV_ROOT"/*) return 0 ;;
  esac

  if [ -e "$dst" ]; then
    if [ "${HV_DRY_RUN:-0}" = "1" ]; then
      hv::log "would copy ~/.zshrc.d/local.zsh (currently -> $target) into a real file"
      return 0
    fi
    local content
    content="$(cat "$dst")"
    hv::run rm -f "$dst"
    printf '%s\n' "$content" > "$dst"
    hv::warn "local.zsh was a symlink into $target -- copied its contents into a real file at ~/.zshrc.d/local.zsh so they don't dangle when that repo goes away"
  else
    if [ "${HV_DRY_RUN:-0}" = "1" ]; then
      hv::log "would replace dangling ~/.zshrc.d/local.zsh (-> $target) with the standard stub"
      return 0
    fi
    hv::run rm -f "$dst"
    hv::_write_local_zsh_stub
    hv::warn "local.zsh was a dangling symlink (-> $target) -- replaced ~/.zshrc.d/local.zsh with the standard stub"
  fi
}

hv_step_run() {
  hv::step 40 "symlinks"

  local src dst f
  while IFS=$'\t' read -r src dst; do
    hv::link "$src" "$dst"
  done <<EOF
$(hv::_pairs)
EOF

  hv::run mkdir -p "$HOME/.local/bin" "$HOME/.zshrc.d" "$HOME/.zsh/cache"

  for f in "$HV_ROOT"/zsh/.zshrc.d/*.zsh; do
    hv::link "$f" "$HOME/.zshrc.d/$(basename "$f")"
  done

  for f in "$HV_ROOT"/bin/*; do
    [ -x "$f" ] || continue
    hv::link "$f" "$HOME/.local/bin/$(basename "$f")"
  done

  hv::_write_git_local

  if [ ! -f "$HOME/.secrets" ] && [ "${HV_DRY_RUN:-0}" != "1" ]; then
    cat > "$HOME/.secrets" <<'EOF'
# Secrets — never commit this file.
# export GITHUB_TOKEN=""
# export ANTHROPIC_API_KEY=""
EOF
    chmod 600 "$HOME/.secrets"
    hv::ok "created ~/.secrets"
  fi

  hv::_reconcile_local_zsh

  if [ ! -f "$HOME/.zshrc.d/local.zsh" ] && [ "${HV_DRY_RUN:-0}" != "1" ]; then
    hv::_write_local_zsh_stub
    hv::ok "created ~/.zshrc.d/local.zsh"
  fi

  if [ ! -f "${HV_CONFIG_HOME:-$HOME/.config/hv}/local.Brewfile" ] && [ "${HV_DRY_RUN:-0}" != "1" ]; then
    hv::run mkdir -p "${HV_CONFIG_HOME:-$HOME/.config/hv}"
    hv::_write_local_brewfile_stub
    hv::ok "created ~/.config/hv/local.Brewfile"
  fi

  return 0
}
